apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: instagram
  template:
    metadata:
      labels:
        app: instagram
    spec:
      containers:
      - name: instagram
        image: praveenhema/instagram:latest
        ports:
        - containerPort: 3000  # Port your application listens on
